### ISSUE TITLE
Error when learnrate not specified (ppo-cnn)

### ISSUE THREAD

**Issue by david-lindner** [jvmancuso/safe-grid-agents#59]
For the ppo-cnn agent (and potentially others as well) the learning rate seems to be a required argument. However, if `-l` is not specified the run crashes instead of given a reasonable message that I forgot a required argument.

Reproduce by:
```
python main.py -E 10000 -V 50 -EE 10 -C -L runs/way/ppo-cnn/cheat way ppo-cnn -e 10 -r 200
```
which gives
```
/home/david/.local/lib/python3.7/site-packages/gym-0.11.0-py3.7.egg/gym/logger.py:30: UserWarning: WARN: Could not seed environment <BaseGridworld<ToyGridworldOnTheWay-v0>>
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    train(args)
  File "/home/david/safe-grid-agents/train.py", line 54, in train
    agent = agent_class(env, args)
  File "/home/david/safe-grid-agents/safe_grid_agents/common/agents/policy_cnn.py", line 15, in __init__
    super().__init__(env, args)
  File "/home/david/safe-grid-agents/safe_grid_agents/common/agents/policy_base.py", line 42, in __init__
    self.optim = torch.optim.Adam(self.parameters(), self.lr)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/optim/adam.py", line 32, in __init__
    if not 0.0 <= lr:
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
```

**Comment by jvmancuso** [comment]
fixed in #61
